### ISSUE TITLE
npm package missing

### ISSUE THREAD

**Issue by niklaswolf** [meeshoogendoorn/shopware-frontends-proxy#1]
I'd really like to try this, but right now the npm package mentioned in the Readme-file is not available :(
`shopware-frontends-proxy`

**Comment by meeshoogendoorn** [comment]
I accidentally removed the shopware-frontends-proxy npm package today. 😢
I will republish tomorrow because I have to wait 24 hours to republish. 😄

**Comment by niklaswolf** [comment]
Nice, Christmas-release 🎄 🎁

**Comment by meeshoogendoorn** [comment]
Package published 😄
